---
services:
  mariadb:
    build: ./mariadb
  nginx:
    build: ./nginx
    volumes: 
      - wordpress_data:/usr/share/nginx/slakner.
    ports:
      - 443:443
  wordpress:
    build: ./wordpress
      - wordpress_data:/wordpress

volumes:
  wordpresss_data: