---
version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    env_file: ./.env
    restart: unless-stopped
    volumes: 
      - database:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 2323:443
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/wordpress
    depends_on:
      - mariadb
    env_file: ./.env
volumes:
  wordpress_data:
  database:
