---
services:
  mariadb:
    build: ./requirements/mariadb
    expose: # expose allows access to 3306 only for other containers
      - "3306"
  nginx:
    build: ./requirements/nginx
    volumes: 
      - wordpress_data:/usr/share/nginx/
    ports:
      - 443:443
  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/wordpress
    expose:
      - "9000"

volumes:
  wordpress_data: