---
version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    env_file: ./.env
    restart: unless-stopped
    volumes: 
      - database:/var/lib/mysql
    networks:
      - inception_network

  nginx:
    build: ./requirements/nginx
    volumes: 
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: unless-stopped
    networks:
      - inception_network

  wordpress:
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    env_file: ./.env
    restart: unless-stopped
    networks:
      - inception_network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/slakner/data/wordpress
      o: bind
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/slakner/data/mariadb
      o: bind

networks:
  inception_network:
